#!/usr/bin/env python3
"""Rasterize ASCII 32..126 into an 8x16 bitmap atlas -> main/font.c + main/font.h.

Generated once and committed; re-run only to change the font. One byte per row,
MSB = leftmost pixel. Uses a system monospace TTF (DejaVu Sans Mono).

Usage: gen_font.py [main_dir]   (default: ../main relative to this script)
"""

import os
import sys

from PIL import Image, ImageDraw, ImageFont

FONT_W, FONT_H = 8, 16
FIRST, LAST = 32, 126
TTF = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"


def glyph_rows(font, ch):
    img = Image.new("L", (FONT_W, FONT_H), 0)
    d = ImageDraw.Draw(img)
    # Nudge so the monospace cell sits nicely in 8x16.
    d.text((0, -1), ch, fill=255, font=font)
    rows = []
    px = img.load()
    for y in range(FONT_H):
        bits = 0
        for x in range(FONT_W):
            if px[x, y] > 110:
                bits |= 1 << (FONT_W - 1 - x)
        rows.append(bits)
    return rows


def main(argv):
    main_dir = argv[1] if len(argv) > 1 else os.path.join(os.path.dirname(__file__), "..", "main")
    font = ImageFont.truetype(TTF, 14)

    lines = [
        "// GENERATED by tools/gen_font.py from DejaVu Sans Mono. Do not edit.",
        '#include "font.h"',
        "",
        f"const uint8_t font8x16[{LAST - FIRST + 1}][FONT_H] = {{",
    ]
    for code in range(FIRST, LAST + 1):
        rows = glyph_rows(font, chr(code))
        body = ", ".join(f"0x{r:02x}" for r in rows)
        lines.append(f"    {{ {body} }},  // {code} {chr(code)!r}")
    lines.append("};")
    with open(os.path.join(main_dir, "font.c"), "w") as fh:
        fh.write("\n".join(lines) + "\n")

    with open(os.path.join(main_dir, "font.h"), "w") as fh:
        fh.write(
            "// GENERATED by tools/gen_font.py. Do not edit.\n"
            "#pragma once\n"
            "#include <stdint.h>\n"
            f"#define FONT_W {FONT_W}\n"
            f"#define FONT_H {FONT_H}\n"
            f"#define FONT_FIRST {FIRST}\n"
            f"#define FONT_LAST {LAST}\n"
            "extern const uint8_t font8x16[FONT_LAST - FONT_FIRST + 1][FONT_H];\n"
        )
    print(f"wrote font.c + font.h ({LAST - FIRST + 1} glyphs) to {main_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
