// GENERATED by tools/gen_font.py. Do not edit.
#pragma once
#include <stdint.h>
#define FONT_W 8
#define FONT_H 16
#define FONT_FIRST 32
#define FONT_LAST 126
extern const uint8_t font8x16[FONT_LAST - FONT_FIRST + 1][FONT_H];
